'use strict';
const D=window.TEST_DATA;
const dimensions=[['角色还原度','语气、想法、反应是否真的像这个角色'],['情绪深度','有没有写出聊天中没直接说出的心理，而不是复述聊天'],['日记真实感','像不像私人日记'],['生活感','是否让角色有聊天之外的存在感'],['阅读吸引力','作为用户，你愿不愿意把这篇看完']];
const labels=['很不符合','不太符合','一般','比较符合','非常符合'];
function shuffle(items){const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result}
const state={stage:0,index:0,order:shuffle(D.articles.map(a=>a.id)),ratings:{},accepted:false};
const app=document.querySelector('#app');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function rich(s){return esc(s).replace(/&lt;(\/?)(mark|del|u|pink)&gt;/g,(_,close,tag)=>tag==='pink'?(close?'</span>':'<span class="pink">'):`<${close}${tag}>`)}
function complete(id){return (state.ratings[id]||[]).filter(v=>Number.isInteger(v)&&v>=1&&v<=5).length===5}
function count(){return state.order.filter(complete).length}
function steps(){return `<nav class="steps" aria-label="测试流程">${['了解维度','阅读背景','日记盲测','查看结果'].map((s,i)=>`${i?'<span class="step-line"></span>':''}<span class="step ${state.stage===i?'active':''}" ${state.stage===i?'aria-current="step"':''}><b>${i+1}</b>${s}</span>`).join('')}</nav>`}
function reference(){return `<section class="profile"><div class="eyebrow">CHARACTER PROFILE</div><h2>${esc(D.name)}</h2><p>${esc(D.profile)}</p></section><h2>聊天记录</h2><div class="chat-list">${D.chat.map(line=>{const user=line.startsWith('用户：');return `<div class="chat-message ${user?'user':''}"><b>${user?'用户':'角色'}</b><p>${esc(line.replace(/^(角色|用户)：/,''))}</p></div>`}).join('')}</div>`}
function intro(){return `${steps()}<div class="eyebrow">DIARY EVALUATION / 01</div><h1>一篇好日记，值得从五个角度读。</h1><p class="intro">你将阅读同一角色的 16 篇日记。先熟悉以下维度，再按自己的真实感受评分。</p><div class="intro-layout"><div><div class="dimension-list">${dimensions.map(([title,hint],i)=>`<div class="dimension"><span class="dimension-number">0${i+1}</span><div><h3>${title}</h3><p>${hint}</p></div></div>`).join('')}</div><div class="actions"><span class="small-note">没有标准答案，你的阅读感受就是判断依据。</span><button class="primary" data-action="background">了解人设与聊天记录</button></div></div><aside class="side-note"><h3>如何打分</h3><p>每个维度有五个圆圈，点击第几个圆圈，就代表给出几分。</p><div class="scale-demo" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></div><div class="scale-labels"><span>1 分 · 很不符合</span><span>5 分 · 非常符合</span></div><div class="note-divider"></div><h3>凭感受，独立判断</h3><p>文章以随机顺序出现，评分时不展示提示词来源。每篇都可以回看、修改评分。</p><p>完成全部评分后，再揭晓对比结果。</p></aside></div>`}
function background(){return `${steps()}<div class="eyebrow">BEFORE YOU READ / 02</div><h1>先认识他，再读他的日记。</h1><p class="intro">以下是所有待测日记共同的人设与聊天背景。测试中也可以随时回看。</p>${reference()}<div class="actions"><button class="secondary" data-action="intro">返回评分说明</button><label class="check-label"><input id="accepted" type="checkbox" ${state.accepted?'checked':''}>我已阅读人设与完整聊天记录</label><button class="primary" data-action="start" ${state.accepted?'':'disabled'}>开始盲测</button></div>`}
function ratingPanel(id){const values=state.ratings[id]||[];return `<h2>这篇日记，你怎么看？</h2><p class="small-note">每个维度独立评分，1–5 分。</p>${dimensions.map(([title,hint],d)=>`<section class="rating-row"><div class="rating-title" id="dimension-${d}">${title}<span>${values[d]?values[d]+' / 5':'未评分'}</span></div><p class="rating-hint">${hint}</p><div class="circles" role="group" aria-labelledby="dimension-${d}">${[1,2,3,4,5].map(v=>`<button class="circle ${v<=values[d]?'filled':''}" aria-pressed="${values[d]===v}" aria-label="${title} ${v} 分，${labels[v-1]}" data-dimension="${d}" data-value="${v}">${v}</button>`).join('')}</div></section>`).join('')}<div class="rating-scale"><span>1 分 · 很不符合</span><span>5 分 · 非常符合</span></div><div class="article-nav"><button class="arrow" data-action="previous" aria-label="上一篇" ${state.index===0?'disabled':''}>←</button><span class="small-note">${String(state.index+1).padStart(2,'0')} / 16</span><button class="arrow" data-action="next" aria-label="下一篇" ${state.index===15?'disabled':''}>→</button></div><div class="jump-grid" aria-label="跳转文章">${state.order.map((x,i)=>`<button class="jump ${complete(x)?'done':''} ${i===state.index?'current':''}" data-jump="${i}" aria-label="第 ${i+1} 篇，${complete(x)?'已完成':'未完成'}" ${i===state.index?'aria-current="true"':''}>${i+1}</button>`).join('')}</div><button class="primary" data-action="results" ${count()===16?'':'disabled'}>查看测试结果</button><p class="small-note save-note" role="status">${count()===16?'全部评分完成，可以查看结果。':`已完成 ${count()} / 16 篇，全部完成后解锁结果。`}</p>`}
function test(){const id=state.order[state.index],article=D.articles.find(a=>a.id===id);return `${steps()}<div class="test-heading"><div><div class="eyebrow">BLIND READING / 03</div><h1>读一篇日记，靠近一个角色。</h1></div><button class="secondary" data-action="reference">回看人设与聊天</button></div><div class="progress-track" role="progressbar" aria-label="已完成文章" aria-valuenow="${count()}" aria-valuemin="0" aria-valuemax="16"><span style="width:${count()/16*100}%"></span></div><div class="test-layout"><article class="paper"><div class="paper-label"><span>日记 ${String(state.index+1).padStart(2,'0')}</span><span>来源已隐藏</span></div><div class="article-body">${article.paragraphs.map(p=>`<p>${rich(p)}</p>`).join('')}</div></article><aside class="rating-panel">${ratingPanel(id)}</aside></div><p class="footer-note">可用左右方向键切换文章 · 评分仅保留在当前页面，关闭或刷新会重置</p>`}
function statistics(){if(count()!==16)throw Error('请先完成全部评分');return ['提示词 1','提示词 2','旧提示词'].map(group=>{const articles=D.articles.filter(a=>a.group===group);const sums=dimensions.map((_,i)=>articles.reduce((sum,a)=>sum+state.ratings[a.id][i],0));return {group,n:articles.length,means:sums.map(v=>v/articles.length),total:sums.reduce((a,b)=>a+b,0),average:sums.reduce((a,b)=>a+b,0)/(articles.length*5)}})}
function results(){const stats=statistics(),best=Math.max(...stats.map(g=>g.average));return `${steps()}<div class="eyebrow">THE RESULTS / 04</div><h1>你的判断，已经有了答案。</h1><p class="intro">16 篇日记，80 项评分。以下是你本次测试中，对三组提示词的评价。</p><div class="result-grid">${stats.map(g=>`<section class="result-card ${g.average===best?'best':''}"><div class="result-label"><h3>${g.group}</h3>${g.average===best?'<span class="badge">综合均分最高</span>':''}</div><div class="score">${g.average.toFixed(2)} <small>/ 5</small></div><span class="small-note">${g.n} 篇文章 · 原始总分 ${g.total} / ${g.n*25}</span></section>`).join('')}</div><h2>五个维度，分别比较</h2><div class="table-wrap"><table><thead><tr><th>评分维度</th>${stats.map(g=>`<th>${g.group}</th>`).join('')}</tr></thead><tbody>${dimensions.map(([name],i)=>`<tr><td>${name}</td>${stats.map(g=>`<td>${g.means[i].toFixed(2)}<span class="bar"><i style="width:${g.means[i]/5*100}%"></i></span></td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="small-note">每个维度取该组文章的平均分；综合均分 = 该组全部评分总和 ÷（文章数 × 5）。三组文章数量不同，因此以均分进行比较。结果仅代表本次测试。</p><details class="review-heading"><summary>查看逐篇评分与来源</summary><div class="table-wrap"><table><thead><tr><th>测试顺序</th><th>原文编号</th><th>提示词</th>${dimensions.map(([name])=>`<th>${name}</th>`).join('')}</tr></thead><tbody>${state.order.map((id,i)=>`<tr><td>${i+1}</td><td>${id}</td><td>${D.articles.find(a=>a.id===id).group}</td>${state.ratings[id].map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div></details><div class="actions"><span class="small-note">分组：原文 1–7 为提示词 1；8–14 为提示词 2；15–16 为旧提示词。</span><button class="secondary" data-action="review">返回修改评分</button></div>`}
function render(scroll=true){app.innerHTML=[intro,background,test,results][state.stage]();if(scroll)window.scrollTo({top:0,behavior:'instant'})}
function rate(d,v){if(state.stage!==2||!Number.isInteger(d)||d<0||d>4||!Number.isInteger(v)||v<1||v>5)throw Error('评分参数无效');const id=state.order[state.index];if(!state.ratings[id])state.ratings[id]=Array(5).fill(null);state.ratings[id][d]=v;document.querySelector('.rating-panel').innerHTML=ratingPanel(id);const bar=document.querySelector('.progress-track');bar.setAttribute('aria-valuenow',count());bar.firstElementChild.style.width=count()/16*100+'%'}
function move(i){if(i<0||i>15)return;state.index=i;render()}
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.dimension!==undefined){const d=Number(b.dataset.dimension),v=Number(b.dataset.value);rate(d,v);document.querySelector(`[data-dimension="${d}"][data-value="${v}"]`).focus({preventScroll:true});return}if(b.dataset.jump!==undefined){move(Number(b.dataset.jump));return}switch(b.dataset.action){case 'background':state.stage=1;render();break;case 'intro':state.stage=0;render();break;case 'start':if(state.accepted){state.stage=2;render()}break;case 'reference':document.querySelector('#reference-content').innerHTML=reference();document.querySelector('#reference').showModal();break;case 'previous':move(state.index-1);break;case 'next':move(state.index+1);break;case 'results':if(count()===16){state.stage=3;render()}break;case 'review':state.stage=2;render();break}});
app.addEventListener('change',e=>{if(e.target.id==='accepted'){state.accepted=e.target.checked;app.querySelector('[data-action="start"]').disabled=!state.accepted}});
document.querySelector('#close-reference').addEventListener('click',()=>document.querySelector('#reference').close());
document.addEventListener('keydown',e=>{if(state.stage!==2||document.querySelector('#reference').open||e.altKey||e.ctrlKey||e.metaKey)return;if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();move(state.index+(e.key==='ArrowRight'?1:-1))}});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_diary_test_progress',description:'读取当前日记盲测进度，不揭晓未完成测试的提示词分组。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({stage:state.stage,completed:count(),total:16,currentPosition:state.index+1})})).catch(()=>{})}catch{}}
render();


